---
title: "Simulations Combined"
author: "Erin M. Buchanan"
date: "`r Sys.Date()`"
output: html_document
---

## Libraries

```{r}
library(rio)
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)
library(papaja)
library(broom)
```

## Data

```{r import-data}
summary_long <- bind_rows(
  import(here("simulation_study/simulation_middle/simulated_summary_data_middle.csv")) %>% mutate(sim = "middle"), 
  import(here("simulation_study/simulation_ceiling/simulated_summary_data_ceiling.csv")) %>% mutate(sim = "ceiling"))
```

## Check for Zero Variance

```{r}
zero <- summary_long %>% 
  mutate(sd_item = round(sd_item, digits = 4)) %>% 
  filter(sd_item < 0.05) %>% 
  group_by(variability, original_n, scale_size, sim) %>% 
  summarize(count = n() / (10*4)) # 10 deciles by 4 powers

zero
```

## Check the Variances

```{r}
rest <- summary_long %>% 
  filter(sd_item > .05) %>% 
  group_by(scale_size, original_n, variability, sim) %>% 
  summarize(variance = mean(sd_item))

rest

ggplot(rest %>% filter(scale_size == "Likert"), 
       aes(variability, variance, color = sim)) + 
  #facet_wrap(~scale_size) + 
  geom_jitter() + 
  geom_boxplot() + 
  theme_linedraw() + 
  xlab("Amount of Simulated Variance") + 
  ylab("Variance Found") + 
  scale_color_discrete(name = "Simulation Type", 
                       labels = c("Ceiling", "Average")) +
  ggtitle("Likert Scale")

ggplot(rest %>% filter(scale_size == "Percent"), 
       aes(variability, variance, color = sim)) + 
  #facet_wrap(~scale_size) + 
  geom_jitter() + 
  geom_boxplot() + 
  theme_linedraw() + 
  xlab("Amount of Simulated Variance") + 
  ylab("Variance Found") + 
  scale_color_discrete(name = "Simulation Type", 
                       labels = c("Ceiling", "Average")) + 
  ggtitle("Percent Scale")

ggplot(rest %>% filter(scale_size == "Milliseconds"), 
       aes(variability, variance, color = sim)) + 
  #facet_wrap(~scale_size) + 
  geom_jitter() + 
  geom_boxplot() + 
  theme_linedraw() + 
  xlab("Amount of Simulated Variance") + 
  ylab("Variance Found" )+ 
  scale_color_discrete(name = "Simulation Type", 
                       labels = c("Ceiling", "Average")) +
  ggtitle("Millisecond Scale")
```

